{-
   This file is automatically generated by elm-graphql. Do not modify!
-}


module GraphQL.Music exposing (search, SearchResult, lists, ListsResult)

import Task exposing (Task)
import Json.Decode exposing (..)
import Json.Encode exposing (encode)
import Http
import GraphQL exposing (apply, maybeEncode, ID)


endpointUrl : String
endpointUrl =
    "http://localhost:5000/graphql"


type alias SearchResult =
    { searchTracks :
        List
            { name : Maybe String
            , youtubeId : Maybe String
            , artists :
                List
                    { name : Maybe String
                    }
            }
    }


search :
    { query : String
    }
    -> Task Http.Error SearchResult
search params =
    let
        graphQLQuery =
            """query search($query: String!) { searchTracks(query: $query) { name youtubeId artists { name } } }"""
    in
        let
            graphQLParams =
                Json.Encode.object
                    [ ( "query", Json.Encode.string params.query )
                    ]
        in
            GraphQL.query endpointUrl graphQLQuery "search" (encode 0 graphQLParams) searchResult


searchResult : Decoder SearchResult
searchResult =
    map SearchResult
        ("searchTracks"
            := (list
                    (map (\name youtubeId artists -> { name = name, youtubeId = youtubeId, artists = artists }) (maybe ("name" := string))
                        `apply` (maybe ("youtubeId" := string))
                        `apply`
                            ("artists"
                                := (list (map (\name -> { name = name }) (maybe ("name" := string))))
                            )
                    )
               )
        )


type alias ListsResult =
    { myLists :
        List
            { id : String
            , name : Maybe String
            , tracks :
                List
                    { name : Maybe String
                    , duration : Maybe String
                    , artists : Maybe String
                    , youtubeId : Maybe String
                    }
            }
    }


lists : Task Http.Error ListsResult
lists =
    let
        graphQLQuery =
            """query lists { myLists { id name tracks { name duration artists youtubeId } } }"""
    in
        let
            graphQLParams =
                Json.Encode.object
                    []
        in
            GraphQL.query endpointUrl graphQLQuery "lists" (encode 0 graphQLParams) listsResult


listsResult : Decoder ListsResult
listsResult =
    map ListsResult
        ("myLists"
            := (list
                    (map (\id name tracks -> { id = id, name = name, tracks = tracks }) ("id" := string)
                        `apply` (maybe ("name" := string))
                        `apply`
                            ("tracks"
                                := (list
                                        (map (\name duration artists youtubeId -> { name = name, duration = duration, artists = artists, youtubeId = youtubeId }) (maybe ("name" := string))
                                            `apply` (maybe ("duration" := string))
                                            `apply` (maybe ("artists" := string))
                                            `apply` (maybe ("youtubeId" := string))
                                        )
                                   )
                            )
                    )
               )
        )
