{-
    This file is automatically generated by elm-graphql. Do not modify!
-}
module GraphQL.Playlists exposing (allPlaylists, AllPlaylistsResult)

import Task exposing (Task)
import Json.Decode exposing (..)
import Json.Encode exposing (encode)
import Http
import GraphQL exposing (apply, maybeEncode, ID)

endpointUrl : String
endpointUrl =
    "http://localhost:5000/playlists/graphql"


type alias AllPlaylistsResult 
    = { allPlaylists : (List     { id : String
    , name : (Maybe String)
    , tracks : (List         { name : (Maybe String)
        , artists : (Maybe String)
        , duration : (Maybe String)
        , youtubeId : (Maybe String)
        })
    })
}


allPlaylists : Task Http.Error AllPlaylistsResult
allPlaylists =
    let graphQLQuery = """query allPlaylists { allPlaylists { id name tracks { name artists duration youtubeId } } }""" in
    let graphQLParams =
            Json.Encode.object
                [ 
                ]
    in
    GraphQL.query endpointUrl graphQLQuery "allPlaylists" (encode 0 graphQLParams) allPlaylistsResult


allPlaylistsResult : Decoder AllPlaylistsResult
allPlaylistsResult =
    map AllPlaylistsResult ("allPlaylists" :=
        (list (map (\id name tracks -> { id = id, name = name, tracks = tracks }) ("id" := string)
        `apply` (maybe ("name" := string))
        `apply` ("tracks" :=
        (list (map (\name artists duration youtubeId -> { name = name, artists = artists, duration = duration, youtubeId = youtubeId }) (maybe ("name" := string))
        `apply` (maybe ("artists" := string))
        `apply` (maybe ("duration" := string))
        `apply` (maybe ("youtubeId" := string))))))))
