viewNav =
    nav [ class "nav" ]
        [ div [ class "nav-left" ]
            [ a [ class "nav-item is-brand", href "#" ]
                [ h1 [ class "title" ] [ text "Music" ] ]
            , a [ class "nav-item", href "#" ]
                [ text "Home    " ]
            , a [ class "nav-item", href "#" ]
                [ text "Documentation    " ]
            , a [ class "nav-item", href "#" ]
                [ text "Blog    " ]
            ]
        , div [ class "nav-center" ]
            [ p [ class "nav-item   control has-addons" ]
                [ input
                    [ class "input", placeholder "Find music", type' "text" ]
                    []
                , button
                    [ class "button is-info" ]
                    [ text "Search" ]
                ]
            ]
        ]
